
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-x-hidden`}
      >
        {children}
       <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              borderRadius: '8px',
              padding: '12px 16px',
              fontSize: '0.95rem',
              fontWeight: 500,
              color: '#fff',
              boxShadow: '0 4px 10px rgba(0,0,0,0.15)',
            },
            success: {
              style: {
                background: '#16a34a', // verde
              },
              iconTheme: {
                primary: '#fff',
                secondary: '#16a34a',
              },
            },
            error: {
              style: {
                background: '#dc2626', // vermelho
              },
              iconTheme: {
                primary: '#fff',
                secondary: '#dc2626',
              },
            },
            loading: {
              style: {
                background: '#6b7280', // cinza
              },
              iconTheme: {
                primary: '#fff',
                secondary: '#6b7280',
              },
            },
            custom: {
              style: {
                background: '#6b7280', // cinza
              },
              iconTheme: {
                primary: '#fff',
                secondary: '#6b7280',
              },
            },
            blank: {
              style: {
                background: '#f97316', // laranja
              },
              iconTheme: {
                primary: '#fff',
                secondary: '#f97316',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
